apiVersion: apps/v1
kind: Deployment
metadata:
  name: halloween-deployment
  labels:
    app: halloween
spec:
  replicas: 3
  selector:
    matchLabels:
      app: halloween
  template:
    metadata:
      labels:
        app: halloween
    spec:
      containers:
      - name: halloween-container
        image: versage/halloween:v1
 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: halloween-service
spec:
  selector:
    app: halloween
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004