apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixer-deployment
  labels:
    app: mixer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mixer
  template:
    metadata:
      labels:
        app: mixer
    spec:
      containers:
      - name: mixer-container
        image: versage/mixer:m1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mixer-service
spec:
  selector:
    app: mixer
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000  # Change this to desired NodePort number
