apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: devopseasylearning/banga-db:v0.0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        volumeMounts:
        - name: val1
          mountPath: /var/lib/mysql
      volumes:
      - name: val1
        emptyDir: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  volumeClaimTemplates:
  - metadata:
      name: val1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  selector:
    matchLabels:
      app: db
  serviceName: db
  
