apiVersion: apps/v1
kind: Deployment
metadata:
  name: wather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wather
  template:
    metadata:
      labels:
        app: wather
    spec:
      containers:
        - name: wather
          hostname: val1
          image: devopseasylearning/banga-wather:v0.0.1
          ports:
            - containerPort: 5000
          env:
            - name: APIKEY
              value: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
          
            
    
---
apiVersion: v1
kind: Service
metadata:
  name: wather
spec:
  selector:
    app: wather
  ports:
    - protocol: TCP
      port: 5500
      targetPort:5000
  type: ClusterIP   