apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
  labels:
    wide: odilia
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: yelb-appserver
  template:
    metadata:
      labels:
        app: yelb-appserver
        wide: odilia
    spec:
      containers:
      - name: yelb-appserver
        image: mreferre/yelb-appserver:0.7
        ports:
        - containerPort: 4567


---
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
spec:
  type: ClusterIP
  selector:
    app: yelb-appserver
    wide: odilia
  ports:
  - protocol: TCP
    name: server
    port: 4567
    targetPort: 4567
