apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    wide: odilia
spec:
  replicas: 2
  serviceName: redis-server
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        wide: odilia
    spec:
      containers:
      - name: redis-server
        image: redis:latest
        ports:
        - containerPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  selector:
    app: redis-server
    wide: odilia
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
