apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-ui
  labels:
    wide: odilia
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: yelb-ui
  template:
    metadata:
      labels:
        app: yelb-ui
        wide: odilia
    spec:
      containers:
      - name: yelb-ui
        image: mreferre/yelb-ui:0.10
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
spec:
  type: NodePort
  selector:
    app: yelb-ui
    wide: odilia
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30101 
