apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: val1
        image: devopseasylearning/tarzan-ui:v0.0.1
        ports:
        - containerPort: 3000
        env:
        - name: AUTH_HOST
          value: auth
        - name: WEATHER_HOST
          value: weather
        - name: AUTH_PORT
          value: "8080"
        - name: WEATHER_PORT
          value: "5000"
        - name: REDIS_USER
          value: redis
        - name: REDIS_PASSWORD
          value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
