version: '3.3'

services:
  ui:
    container_name: ver1 
    hostname: val1
    image: devopseasylearning/banga-ui:v0.0.1
    ports:
      - "4500:3000"
    environment:
      - AUTH_HOST=auth
      - WEATHER_HOST=weather
      - AUTH_PORT=8080
      - WEATHER_PORT=5000
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    depends_on:
      - auth
   
     
    networks:
      - versage1
    restart: always

  auth:
    container_name: ver2
    hostname:  val2
    image: devopseasylearning/banga-auth:v0.0.1
    expose: 
      - "8080" 
    ports:
      - 8003:8080
    environment:
      - DB_HOST=db
      - DB_PASSWORD=my-secret-pw
    depends_on:
      - weather 
    networks:
      - versage1
    restart: always

  weather:
    container_name: ver3
    hostname:  val3
    image:  devopseasylearning/banga-weather:v0.0.1
    ports:
      - "4050:5000"
    environment:
      - APIKEY=ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    depends_on:
      - db
    networks:
      - versage1
    restart: always

     
  

  db:
    container_name: ver4
    hostname:  val4
    image:  devopseasylearning/banga-db:v0.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - val1:/var/lib/mysql
    networks:
      - versage1
    restart: always

  redis:
    container_name: ver5
    hostname:  val5
    image: redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    volumes:
      - val2:/data
    networks:
      - versage1s
    restart: always
    depends_on:
      - ui

volumes:
  val1:
  val2:

networks:
  versage1:
    driver: bridge