version: '3.3'

services:

    frontend:
      build:
        context: ./
        dockerfile: Dockerfileworker
      ports:
        - 3000:3000
     environment:
        - DATABASE_HOST=database 
        - DATABASE_PORT=5432
      depends_on:
        - database
        - worker  
      networks: 
        - valdes     
    
    worker:
      build:
        context: ./
        dockerfile: Dockerfile-frontend-worker
      environment:
        - DATABASE_HOST=database 
        - DATABASE_PORT=5432
      depends_on:
        - database
      networks: 
        - valdes  
    storefront:
      build:
        context: .
        dockerfile: Dockerfile-storefront 
      ports: 
        - 4000:4000
      environment:
        - SERVER_API_HOST=http://server 
        - SERVER_API_PORT=3000
        - SERVER_API_PATH=shop-api
      depenps_on:
        - database
      networks:
        - valdes
    database:
      image: postgres:14
      environment: 
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=VENDURE 
      expose:
        - "5432"
      ports:
        - "5000:5432"
      volumes:
        - vol1:/var/lib/postgresql/data
      networks:
        - valdes  
    dbreplica:
      image: postgres:14
      environment: 
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=VENDURE 
      expose:
        - "5432"
      ports:
        - "5001:5432"
      volumes:
        - vol2:/var/lib/postgresql/data
      networks:
        - valdes             
    mariadb: 
      image: mariadb:10.6
      environment: 
        - MYSQL_PASSWORD=password
      ports:
        - 3500:3306
      volumes:
        - mariadb:/var/lib/mysql
      networks:
        - valdes 
    wordpress:
      image: wordpress:4.7-php7.1-apache
      environment:
        - MONEI_OPERATION_MODE=live
        - MONEI_TEST_CHANNEL_ID=test_channel_id
        - MONEI_TEST_USER_ID=test_user_id
        - MONEI_TEST_PASSWORD=test_password 
        - MONEI_LIVE_CHANNEL_ID=live_channel_id
        - MONEI_LIVE_ USER_ID=live_user_id
        - MONEI_LIVE_PASSWORD=live_password
        - WORDPRESS_DB_HOST=mariadb:3306
        - WORDPRESS_DB_PASSWORD=password
        - WORDPRESS_SITE_TITLE=some_site_title
        - WORDPRESS_ADMIN_PASSWORD=1234
      expose: 
        - "80"  
        - "443"
      ports: 
        - "3500:80"
        - "4000:443"  
      depends_on:
        - mariadb  
      networks:
        - valdes n
    
    redis-0:
      image: redis:6.0-alpine 
      ports:
      volumes:
        - redis-0:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf 
      networks:
        - valdes 


    redis-1:
      image: redis:6.0-alpine 
     
      volumes:
        - redis-1:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf 
      networks:
        - valdes

    redis-2:
      image: redis:6.0-alpine 
     
      volumes:
        - redis-2:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf 
      networks:
        - valdes

    sentinel-0:
      images:  redis:6.0-alpine
      volumes:
        - sentinel-0:/etc/redis/sentinel.conf
      command:  redis-sentinel /etc/redis/sentinel.conf 
      networks:
        - valdes 

    sentinel-1:
      images:  redis:6.0-alpine
      volumes:
        - sentinel-1:/etc/redis/sentinel.conf
      command:  redis-sentinel /etc/redis/sentinel.conf 
      networks:
        - valdes

    sentinel-2:
      images:  redis:6.0-alpine
      volumes:
        - sentinel-2:/etc/redis/sentinel.conf
      command:  redis-sentinel /etc/redis/sentinel.conf 
      networks:
        - valdes


networks:
  valdes:
    driver: bridge  

volumes:
  vol1:
    driver: local
  vol2:
    driver: local  
  mariadb:
    driver: local
  redis-0:
    driver: local     
  redis-1: 
    driver: local
  redis-2:
    driver: local 
  sentinel-0:
    driver: local   
  sentinel-1:
    driver: local 
  sentinel-2:
    driver: local

