from httpd
run apt update
run apt install vim -y
run apt install unzip -y
run apt install wget -y
run cd /usr/local/apache2/htdocs
run rm -rf index.html 
run  wget https://warfiles-for-docker.s3.amazonaws.com/app/creative.zip
run unzip creative.zip
run rm -rf creative.zip




run wget https://warfiles-for-docker.s3.amazonaws.com/app/restaurant.zip
run unzip restaurant.zip
run rm -rf restaurant.zip
run cp -r restaurant/* .


run wget https://warfiles-for-docker.s3.amazonaws.com/app/articles.zip
run unzip articles.zip
run rm -rf articles.zip